### ISSUE TITLE
static version - Failed to compile

### ISSUE THREAD

**Issue by SvenMeyer** [juntofoundation/Junto#24]
just cloned the repo
$ cd static
$ npm install
$ npm run dev

`junto-web@1.0.0 dev /home/sum/Dev/hc/Junto/static
cross-env NODE_ENV=development webpack-dev-server --open --hot

Project is running at http://localhost:8080/
webpack output is served from /dist/
404s will fallback to /index.html
Hash: 433de7e99e0ce6685f64
Version: webpack 3.12.0
Time: 578ms
   Asset    Size  Chunks                    Chunk Names
build.js  889 kB       0  [emitted]  [big]  main
   [0] (webpack)/hot/log.js 1.04 kB {0} [built]
   [3] (webpack)/hot/emitter.js 77 bytes {0} [built]
   [4] multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js 52 bytes {0} [built]
   [5] (webpack)-dev-server/client?http://localhost:8080 7.93 kB {0} [built]
   [6] ./node_modules/url/url.js 23.3 kB {0} [built]
  [13] ./node_modules/strip-ansi/index.js 161 bytes {0} [built]
  [14] ./node_modules/ansi-regex/index.js 135 bytes {0} [built]
  [15] ./node_modules/loglevel/lib/loglevel.js 7.86 kB {0} [built]
  [16] (webpack)-dev-server/client/socket.js 1.08 kB {0} [built]
  [18] (webpack)-dev-server/client/overlay.js 3.67 kB {0} [built]
  [20] ./node_modules/html-entities/index.js 231 bytes {0} [built]
  [23] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {0} [built]
  [25] (webpack)/hot/dev-server.js 1.61 kB {0} [built]
  [26] (webpack)/hot/log-apply-result.js 1.31 kB {0} [built]
  [27] ./src/main.js 1.31 kB {0} [built] [failed] [1 error]
    + 13 hidden modules

ERROR in ./src/main.js
Module build failed: Error: Couldn't find preset "env" relative to directory "/home/sum/Dev/hc/Junto"
    at /home/sum/Dev/hc/Junto/static/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/home/sum/Dev/hc/Junto/static/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/sum/Dev/hc/Junto/static/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/sum/Dev/hc/Junto/static/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/sum/Dev/hc/Junto/static/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/sum/Dev/hc/Junto/static/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/sum/Dev/hc/Junto/static/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/sum/Dev/hc/Junto/static/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/sum/Dev/hc/Junto/static/node_modules/babel-loader/lib/index.js:50:20)
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
`

**Comment by jacobmumm** [comment]
Getting the same problem here..

**Comment by jdeepee** [comment]
Hey @SvenMeyer @jacobmumm. Sorry for taking so long to get back to you. We shifted focus over the past months towards developing a centralized solution that can carry us forwards until holochain is ready. Now that holochain is publicly usable we have started shifted resources into holochain development again. 

Thanks for trying out the app early. Unfortunately we are still have quite a way to go before having a fully functioning front-end that is integrated with a holochain backend. If you wish you can compile and run the current version of the app on master - but its still very incomplete - but atleast working now! ;) Keep an eye on the repo for release Alpha 1. Once that is complete be sure to try it out using holochain's holoscape.
